windowrule = match:class steam, workspace 3
windowrule = match:class steam_app, workspace 3
windowrule = match:class gamescope, workspace 3

windowrule = match:class FreeTube, workspace 4
windowrule = match:class vlc, workspace 4

windowrule = match:class Signal, workspace 5
windowrule = match:class Element, workspace 5
windowrule = match:class Jitsi Meet, workspace 5

windowrule = match:class protonvpn-app, workspace special

windowrule = match:class com.stremio.stremio, idle_inhibit fullscreen
windowrule = match:class vlc, idle_inhibit fullscreen

windowrule = match:class xwaylandvideobridge, opacity 0.0 override
windowrule = match:class xwaylandvideobridge, no_anim on
windowrule = match:class xwaylandvideobridge, no_initial_focus on
windowrule = match:class xwaylandvideobridge, max_size 1 1
windowrule = match:class xwaylandvideobridge, no_blur on
