#!/usr/bin/env sh

# progress-notify - Send audio and brightness notifications for dunst

# dependencies: dunstify --urgency=low, ponymix, Papirus (icons)

### How to use: ###
# Pass the values via stdin and provide the notification type
# as an argument. Options are audio, brightness and muted

### Audio notifications ###
#   ponymix increase 5 | notify audio
#   ponymix decrease 5 | notify audio
#   pulsemixer --toggle-mute --get-mute | notify muted
### Brightness notifications ###
#   xbacklight -inc 5  && xbacklight -get | notify brightness
#   xbacklight -dec 5  && xbacklight -get | notify brightness

notifyMuted() {
	volume="$1"
	dunstify --urgency=low -h string:x-canonical-private-synchronous:audio "Muted" -h int:value:"$volume" -t 1500 --icon audio-volume-muted-symbolic
}

notifyAudio() {
	volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')
	wpctl get-volume @DEFAULT_AUDIO_SINK@ | rg -i muted && notifyMuted "$volume" && return

	if [ $volume -eq 0 ]; then
		notifyMuted "$volume"
	elif [ $volume -le 30 ]; then
		dunstify --urgency=low -h string:x-canonical-private-synchronous:audio "Volume" -h int:value:"$volume" -t 1500 --icon audio-volume-low-symbolic
	elif [ $volume -le 70 ]; then
		dunstify --urgency=low -h string:x-canonical-private-synchronous:audio "Volume" -h int:value:"$volume" -t 1500 --icon audio-volume-medium-symbolic
	else
		dunstify --urgency=low -h string:x-canonical-private-synchronous:audio "Volume" -h int:value:"$volume" -t 1500 --icon audio-volume-high-symbolic
	fi
}

notifyBrightness() {
	brightness=$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')

	if [ $brightness -eq 0 ]; then
		dunstify --urgency=low -h string:x-canonical-private-synchronous:brightness "Brightness" -h int:value:"$brightness" -t 1500 --icon display-brightness-symbolic
	elif [ $brightness -le 30 ]; then
		dunstify --urgency=low -h string:x-canonical-private-synchronous:brightness "Brightness" -h int:value:"$brightness" -t 1500 --icon display-brightness-symbolic
	elif [ $brightness -le 70 ]; then
		dunstify --urgency=low -h string:x-canonical-private-synchronous:brightness "Brightness" -h int:value:"$brightness" -t 1500 --icon display-brightness-symbolic
	else
		dunstify --urgency=low -h string:x-canonical-private-synchronous:brightness "Brightness" -h int:value:"$brightness" -t 1500 --icon display-brightness-symbolic
	fi
}

case "$1" in
audio)
	notifyAudio
	;;
brightness)
	notifyBrightness
	;;
*)
	echo "Not the right arguments"
	echo "$1"
	exit 2
	;;
esac
