#!/usr/bin/env sh

up() {
	hyprctl dispatch dpms on
	brightnessctl set +5%
}

down() {
	brightnessctl set 5%-

	brightness=$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')
	if [ $brightness -eq 0 ]; then
		hyprctl dispatch dpms off
		brightnessctl set 1
	fi
}

upS() {
	hyprctl dispatch dpms on
	brightnessctl set +5%
}

downS() {
	brightnessctl set 5%-

	brightness=$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')
	if [ $brightness -eq 0 ]; then
		hyprctl dispatch dpms off
		brightnessctl set 1
	fi
}

case "$1" in
up)
	up
	;;
down)
	down
	;;
upS)
	upS
	;;
downS)
	downS
	;;
*)
	echo "Not the right arguments"
	echo "$1"
	exit 2
	;;
esac
