return {
    {
        "williamboman/mason.nvim",
        opts = {
            ensure_installed = {
                "autopep8",
                "bash-language-server",
                "black",
                "clang-format",
                "clangd",
                "cmake-language-server",
                "cmakelang",
                "cmakelint",
                "codespell",
                "commitlint",
                "cpplint",
                "cpptools",
                "gitlint",
                "isort",
                "json-lsp",
                "lua-language-server",
                "markdown-toc",
                "markdownlint",
                "mypy",
                "python-lsp-server",
                "ruff",
                "rust-analyzer",
                "rustfmt",
                "shfmt",
                "stylua",
                "yaml-language-server",
                "yamlfmt",
                "yamllint",
            },
        },
    },
}
