
[window]
opacity = 1.0

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular"}
size = 12

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

